ColegioApp/urls.py
from django.contrib import admin
from django.urls import path, include
from colegio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('colegio/', include('colegio.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    #path('accounts/', include('registration.backends.admin_approval.urls')),
    path('accounts/profile/',views.first_view),
    
]

colegio/urls.py
from django.urls import path, include
from colegio import views
from django.contrib import admin




urlpatterns = [ 

    # Main view
    path('', views.base, name='base'),

    # --------------------------- GRADOS ---------------------------------

    # List
    path('grados/', views.GradoList.as_view(), name='grado-list'), 
    
    # Create
    path('grado/create', views.GradoCreate.as_view(), name='grado-create'),
    
    # Update
    path('grado/<int:pk>/update', views.GradoUpdate.as_view(), name='grado-update'),
    
    # Detail
    path('grado/<int:pk>/detalles', views.GradoDetail.as_view(), name='grado-detail'),
    
    # Delete
    path('grado/<int:pk>/delete', views.GradoDelete.as_view(), name='grado-delete'),

    # --------------------------- ESTUDIANTES ---------------------------------

    # List
    path('estudiantes/', views.EstudianteList.as_view(), name='estudiante-list'),

    # Filter estudiantes
    path('estudiantes/<int:grado_id>/lista', views.EstudianteListFilter, name='estudiante-filter-list'),
    
    # Create
    path('estudiante/create/', views.EstudianteCreate.as_view(), name='estudiante-create'),
    
    # Detail
    path('estudiante/<int:pk>/detalles', views.EstudianteDetail.as_view(), name='estudiante-detail'), 

    # Update
    path('estudiante/<int:pk>/actualizar/', views.EstudianteUpdate.as_view(),name='estudiante-update'),
    
    # Delete
    path('estudiante/<int:pk>/eliminar/', views.EstudianteDelete.as_view(),name='estudiante-delete'),

]

colegio/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver  
from django.urls import reverse

# Create your models here.
class Grado(models.Model):
    grado = models.CharField(max_length= 10, default='')
    anio = models.CharField(max_length= 10, default='')
    
    def __str__(self):
     return self.grado +" "+ self.anio

class Horario(models.Model):
    fotoHorario = models.ImageField(upload_to='fotos/')

    def __str__(self):
        return str(self.fotoHorario)

class  Estudiante(models.Model):
    carnet = models.CharField(max_length=50, default='')
    nombre = models.CharField(max_length=50, default='')
    apellido = models.CharField(max_length=50, default='')
    seguro = models.CharField(max_length=50, default='')
    foto = models.ImageField( upload_to='fotos/')
    fecha_naci = models.DateField(auto_now_add= False)
    correo = models.CharField(max_length=50, default='')
    grado = models.ForeignKey(Grado, on_delete=models.PROTECT)
    fotoHorario = models.ForeignKey(Horario, on_delete=models.PROTECT)
    
    def __str__(self):
         return self.carnet +" "+ self.nombre +" "+ self.apellido +" "+ self.seguro +" "+ self.correo
    def get_str_url(self):
     return reverse('estudiante-list')

@receiver(post_delete, sender=Estudiante)
def eliminar_Estudiante(sender, instance, **kwargs):
        instance.foto.delete(False)

colegio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from colegio.models import Grado, Estudiante
from django.views.generic import ListView, DetailView 
from django.shortcuts import render 
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView, CreateView, DeleteView 

# Create your views here.
@login_required
def first_view(request):
    #return HttpResponse("<H1>HOLA MUNDO DESDE LA VISTA first_view</H1>")
    return render(request, 'base.html')

@login_required
def grado(request):
    grado_list = Grado.objects.all()
    context = {'object_list': grado_list}
    return render(request, 'colegio/grado.html', context)

@login_required
def grado_detail(request, grado_id):
    grado = Grado.objects.get(id=grado_id)
    context = {'object': grado}
    return render(request, 'colegio/grado_detail.html', context)

@login_required
def grado_list(request, grado_id):
    grado = Grado.objects.get(id=grado_id)
    context = {'object': grado}
    return render(request, 'colegio/grado_list.html', context)
    
@method_decorator(login_required, name='dispatch')
class EstudianteListView(ListView):
    model = Estudiante

@method_decorator(login_required, name='dispatch')
class EstudianteDetailView(DetailView):
    model = Estudiante

def base(request):
     return render(request, 'base.html')

# --------------------------- GRADOS ---------------------------------

class GradoList(ListView):
    model = Grado

class GradoCreate(CreateView):
    model = Grado
    fields = '__all__'
    success_url = reverse_lazy('grado-list')

class GradoUpdate(UpdateView):
    model = Grado
    fields = '__all__'
    success_url = reverse_lazy('grado-list')

class GradoDetail(DetailView):
    model = Grado

class GradoDelete(DeleteView):
    model = Grado
    success_url = reverse_lazy('grado-list')


# --------------------------- ESTUDIANTES ---------------------------------

class EstudianteList(ListView):
    model = Estudiante

class EstudianteCreate(CreateView):
    model = Estudiante
    fields = '__all__'
    success_url = reverse_lazy('estudiante-list')

class EstudianteUpdate(UpdateView):
    model = Estudiante
    fields = '__all__'
    success_url = reverse_lazy('estudiante-list')

class EstudianteDetail(DetailView):
    model = Estudiante

class EstudianteDelete(DeleteView):
    model = Estudiante
    success_url = reverse_lazy('estudiante-list')

def EstudianteListFilter(request, grado_id):
    grado = Grado.objects.filter(id=grado_id) 
    estudiantes = Estudiante.objects.filter(grado=grado_id)
    context = {'estudiantes_data':estudiantes, 'grado_data':grado}
    return render(request, 'colegio/estudiante_filter_list.html', context)

#class EstudianteList(viewsets.ModelViewSet):
	#queryset=Estudiante.objects.all()
	#serializer_class=EstudianteSerializer

#class GradoList(viewsets.ModelViewSet):
    #queryset = Grado.objects.all()
   # serializer_class = GradoSerializer

colegio/templates/base.html
{% extends "adminlte/base.html" %}

 <!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title>COLEGIO</title>
</head>

<body>
    {% block content %}
    <div class="jumbotron text-center">
        <h1>Sistema de colegio</h1>
        <div style="font-size: 1500%"><i class="fa fa-university" aria-hidden="true"></i></div>
    </div>
    {% endblock content %}
</body>

</html>

colegio/templates/colegio/estudiante_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <h1>¿Está seguro que desea eliminar el estudiante {{ object.nombre }} {{ object.apellido }}</h1>
        </div>
        <hr>
        <div class="row">
            <img src="{% static object.foto.url %}" alt="Fotografia {{ object.nombre }}" style="max-width:250px;">
        </div>
        <hr>
        <div class="row">
            <input class="btn btn-danger" type="submit" value="Confirmar" />
            <a class='btn btn-primary' href="{% url 'estudiante-list' %}">Cancelar</a>
        </div>
    </div>
</form>

{% endblock content %}

colegio/templates/colegio/estudiante_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <table class="table text-left">
        <tr >
            <td>
                <div style="width: 200px;"><img class="img-responsive" src="{% static object.foto.url %}" style="max-width:350px;"></div>
            </td>
            <td >
                <div  class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                        Datos de usuario
                    </a>
                    <a href="#" class="list-group-item list-group-item-action">Identificación: <span class="badge badge-primary badge-pill">{{object.carnet}}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Nombre: <span class="badge badge-primary badge-pill">{{object.nombre}}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Apellido: <span class="badge badge-primary badge-pill">{{object.apellido}}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Seguro: <span class="badge badge-primary badge-pill">{{ estudiante.seguro }}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Fecha de nacimiento: <span class="badge badge-primary badge-pill">{{ estudiante.fecha_naci }}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Correo electrónico: <span class="badge badge-primary badge-pill">{{ estudiante.correo }}</span></a>
                    <a href="#" class="list-group-item list-group-item-action">Grado: <span class="badge badge-primary badge-pill">{{ estudiante.grado }}</span></a>
                </div>
                <div>
                    <a class="btn btn-danger" href="{% url 'estudiante-delete' estudiante.pk %}"><i class="fa fa-trash"></i>Eliminar</a>
                    <a class="btn btn-success" href="{% url 'estudiante-update' estudiante.pk %}"><i class="fa fa-edit"></i>Actualizar</a>
                    <a class="btn btn-primary" href="{% url 'estudiante-list' %}"><i class="fa fa-edit"></i>Regresar</a>
                </div>
            </td>
        </tr>
    </table>
</div>
{% endblock content %}

colegio/templates/colegio/estudiante_filter_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="page-header text-center">
        {% for grado in grado_data %}
        <h1>Listado de estudiantes del grado {{grado}}</h1>
        {% endfor %}

    </div>
</div>
<a href="{% url 'estudiante-create' %}" class="btn btn-success btn-rounded"><i class="fa fa-plus-circle"></i> Agregar
    estudiante</a>
<hr>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Identificación</th>
            <th scope="col">Nombres</th>
            <th scope="col">Seguro</th>
            <th scope="col">Fotografia</th>
            <th scope="col">Fecha de nacimiento</th>
            <th scope="col">Email</th>
            <th scope="col">Grado</th>
            <th scope="col">Horario</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for estudiante in estudiantes_data %}
        <tr>
            <td>{{ estudiante.carnet }}</td>
            <td>{{ estudiante.nombre }} {{ estudiante.apellido }}</td>
            <td>{{ estudiante.seguro }}</td>
            <td><img class="img-responsive" src="{% static estudiante.foto.url %}" style="max-width:70px;"></td>
            <td>{{ estudiante.fecha_naci }}</td>
            <td>{{ estudiante.correo }}</td>
            <td>{{ estudiante.grado }}</td>
            <td><img class="img-responsive" src="{% static estudiante.foto.url %}" style="max-width:70px;"></td>
            <td>
                <a class="btn btn-primary" href="{% url 'estudiante-detail' estudiante.pk %}"><i class="fa fa-eye"></i></a>
                <a class="btn btn-success" href="{% url 'estudiante-update' estudiante.pk %}"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger" href="{% url 'estudiante-delete' estudiante.pk %}"><i class="fa fa-trash"></i></a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}

colegio/templates/colegio/estudiante_form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="page-header text-center">
        <h1>Editando {{ estudiante.nombre }} {{ estudiante.apellido }}</h1>
    </div>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Guardar</button>
        <a class="btn btn-primary" href="{% url 'estudiante-list' %}">Cancelar</a>
    </form>
</div>
{% endblock content%}

colegio/templates/colegio/estudiante_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Lista de estudiantes{% endblock title %}

{% block content %}
<div class="container">
    <div class="page-header text-center">
        <h1>Listado de estudiantes</h1>
    </div>
</div>
<a href="{% url 'estudiante-create' %}" class="btn btn-success btn-rounded"><i class="fa fa-plus-circle"></i> Agregar estudiante</a>
<hr>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Identificación</th>
            <th scope="col">Nombres</th>
            <th scope="col">Seguro</th>
            <th scope="col">Fotografia</th>
            <th scope="col">Fecha de nacimiento</th>
            <th scope="col">Email</th>
            <th scope="col">Grado</th>
            <th scope="col">Horario</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for estudiante in object_list %}
        <tr >
            <td>{{ estudiante.carnet }}</td>
            <td>{{ estudiante.nombre }} {{ estudiante.apellido }}</td>
            <td>{{ estudiante.seguro }}</td>
            <td><img class="img-responsive" src="{% static estudiante.foto.url %}" style="max-width:70px;"></td>
            <td>{{ estudiante.fecha_naci }}</td>
            <td>{{ estudiante.correo }}</td>
            <td>{{ estudiante.grado }}</td>
            <td><img class="img-responsive" src="{% static estudiante.foto.url %}" style="max-width:70px;"></td>
            <td>
                <a class="btn btn-primary" href="{% url 'estudiante-detail' estudiante.pk %}"><i class="fa fa-eye"></i></a>
                <a class="btn btn-success" href="{% url 'estudiante-update' estudiante.pk %}"><i class="fa fa-edit"></i></a>
                <a class="btn btn-danger" href="{% url 'estudiante-delete' estudiante.pk %}"><i class="fa fa-trash"></i></a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}

colegio/templates/colegio/grado.html
{% extends 'base.html' %}
{% load static %}
{% block section %}
    <h2>{{ object.name }}</h2>
     <hr>
        {% endblock section %}
        {% block maincontent %}
    <div>
        <table border="1px">
        <tr>
            {% for p in object.estudiante_set.all %}
                <td>
                    <div>{{ p.carnet }}</div>
                        <div>
                            <a href="{% url 'estudiante-detail' p.carnet %}">
                                <img src="{% static p.estudiante.url %}" style="width:200px;height:200px"/>
                            </a>
                        </div>
                </td>
            {% endfor %}
        </table>
    </div>
{% endblock maincontent %} 

colegio/templates/colegio/grado_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <h1>¿Está eguro que desea eliminar el grado {{ object.grado }} - {{ object.anio }}?</h1>
        </div>
        <div class="row text-danger">
            <div class="jumbotron">
                <h1><i class="fa fa-graduation-cap"></i></h1>
            </div>
        </div>
        <div class="row">
            <input class="btn btn-danger" type="submit" value="Confirmar" />
            <a class='btn btn-primary' href="{% url 'grado-list' %}">Cancelar</a>
        </div>
    </div>
</form>

{% endblock content %}

colegio/templates/colegio/grado_detail.html
{% extends 'base.html' %}
{% block content %}
{{ object.grado }} - {{ object.anio }}
<hr>

{% url 'estudiante-filter-list' object.id as url %}


{% endblock content %} 

colegio/templates/colegio/grado_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="page-header text-center">
        <h1>Crear nuevo grado</h1>
    </div>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Guardar</button>
        <a class="btn btn-primary" href="{% url 'grado-list' %}">Cancelar</a>
    </form>
</div>


{% block modalDelete %}

{% endblock modalDelete %}
{% endblock content %}

colegio/templates/colegio/grado_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Lista de grados{% endblock title %}

{% block content %}
<div class="container">
    <div class="page-header text-center">
        <h1>Listado de grados existentes</h1>
    </div>
    <a href="{% url 'grado-create' %}" class="btn btn-success btn-rounded"><i class="fa fa-plus-circle"></i> Agregar grado</a>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Grado</th>
                <th scope="col">Año</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for grado in object_list %}
            <tr>
                <td>{{ grado.grado }}</td>
                <td>{{ grado.anio }} {{ estudiante.apellido }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'estudiante-filter-list' grado.pk %}"><i class="fa fa-eye"></i></a>
                    <a class="btn btn-success" href="{% url 'grado-update' grado.pk %}"><i class="fa fa-edit"></i></a>
                    <a class="btn btn-danger" href="{% url 'grado-delete' grado.pk %}"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
{% endblock content %}

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %} /colegio {% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<i class="fa fa-graduation-cap"></i>{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<i class="fa fa-graduation-cap"></i>  <b>Colegio</b>{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Navegar</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'auth_password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}/accounts{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}NAVEGACIÓN{% endblock %}</li>

            {% block nav_links %}
            <li>
                <a href="{% url 'grado-list' %}">
                    <i class="fa fa-graduation-cap"></i> <span>Grados</span>
                </a>
            </li>
            <li>
                <a href="{% url 'estudiante-list' %}">
                    <i class="fa fa-users" aria-hidden="true"></i> <span>Estudiantes</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-plus-circle"></i> <span>Agregar</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{% url 'grado-create' %}">
                            <i class="fa fa-graduation-cap"></i></i> Grado
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'estudiante-create' %}">
                            <i class="fa fa-users" aria-hidden="true"></i> Estudiante
                        </a>
                    </li>

                </ul>
            </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>